name: Publish Spring Boot JAR

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run Gradle build and publish
        run: cd $GITHUB_WORKSPACE && ./gradlew publish
        env:
          GITLAB_DOMAIN: ${{ secrets.GITLAB_DOMAIN }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_PUBLISH_USERNAME }}
          GITLAB_PAT: ${{ secrets.GITLAB_PUBLISH_PASSWORD }}
